# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kjljFx7T4QJ9DK113KQtN3X2xKK69xyh

# **STREAMLIT APP**
"""

# !pip install -U streamlit
# !pip install -q pyngrok

import tensorflow as tf
import numpy as np
from PIL import Image
import streamlit as st

from tensorflow.keras.models import load_model
import json

model = load_model('PlantVillage.keras')
with open('classes.json','r') as f:
    class_indices = json.load(f)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
import streamlit as st
import numpy as np
from PIL import Image
from tensorflow.keras.models import load_model
import json

st.markdown(
    """
    <style>
    .stApp{
    background: linear-gradient(135deg,#e8f5e9 0%,#f1f8e9 50%,#e0f2f1 100%);

    }
    </style>
     """,
    unsafe_allow_html = True
)

st.set_page_config(
    page_title = "PlantGaurd",
    page_icon = "🪴",
    layout = "centered"


)

#Load class names from classes.json
with open("classes.json","r") as f:
    CLASS_NAMES = json.load(f)

#DISEASE INFORMATION
DISEASE_INFO = {

    "Tomato__Target_Spot": {
        "severity": "Medium",
        "treatment": "Remove infected leaves, avoid overhead watering, improve air circulation, and apply a recommended fungicide."
    },

    "Potato___healthy": {
        "severity": "None",
        "treatment": "🌱 Your plant is healthy! Continue regular watering, provide adequate sunlight, and maintain balanced fertilization."
    },

    "Potato___Early_blight": {
        "severity": "Medium",
        "treatment": "Remove infected leaves, rotate crops, avoid overhead irrigation, and apply a suitable fungicide."
    },

    "Tomato_Early_blight": {
        "severity": "Medium",
        "treatment": "Remove infected leaves, mulch the soil, water at the base of the plant, and use a fungicide if necessary."
    },

    "Pepper___bell___Bacterial_spot": {
        "severity": "Medium",
        "treatment": "Use disease-free seeds, avoid overhead watering, and spray a copper-based bactericide."
    },

    "Tomato_healthy": {
        "severity": "None",
        "treatment": "🌱 Your tomato plant is healthy! Continue proper watering, sunlight, and balanced fertilization."
    },

    "Potato___Late_blight": {
        "severity": "High",
        "treatment": "Remove infected plants immediately, improve drainage, and apply a fungicide such as metalaxyl."
    },

    "Tomato_Bacterial_spot": {
        "severity": "Medium",
        "treatment": "Remove infected leaves, avoid handling wet plants, and spray a copper-based bactericide."
    },

    "Pepper___bell___healthy": {
        "severity": "None",
        "treatment": "🌱 Your pepper plant is healthy! Maintain proper watering, sunlight, and nutrient supply."
    },

    "Tomato_Spider_mites_Two_spotted_spider_mite": {
        "severity": "Medium",
        "treatment": "Spray neem oil or an approved miticide, increase humidity, and remove heavily infested leaves."
    },

    "Tomato__Tomato_YellowLeaf__Curl_Virus": {
        "severity": "High",
        "treatment": "Remove infected plants, control whiteflies using insecticides or sticky traps, and use resistant varieties."
    },

    "Tomato_Leaf_Mold": {
        "severity": "Medium",
        "treatment": "Reduce humidity, improve ventilation, avoid wetting leaves, and apply a fungicide."
    },

    "Tomato_Late_blight": {
        "severity": "High",
        "treatment": "Remove infected foliage immediately, avoid overhead watering, and apply a recommended fungicide."
    }

}


#UI
st.title("PlantGuard🪴")
st.image("images/Project_Banner.jpeg", width=450)
st.header("Know your plant's health💚")

uploaded_file = st.file_uploader( "Upload a leaf image",type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert("RGB")
    st.image(image, caption="Uploaded Image", width=300)

    # Preprocess
    img = image.resize((224, 224))
    img_array = np.array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    #Cache model so it loads only once
    @st.cache_resource
    def load_my_model():
        return load_model("PlantVillage.keras")

    model = load_my_model()
    predictions = model.predict(img_array)

    confidence = np.max(predictions) * 100
    predicted_class = CLASS_NAMES[np.argmax(predictions)]

    # Display results
    st.markdown("---")
    st.subheader("🔍 Prediction Result")
    st.success(f"**Disease:** {predicted_class.replace('_', ' ')}")
    st.info(f"**Confidence Score:** {confidence:.2f}%")
    st.progress(int(confidence))

    st.markdown("---")
    st.subheader("💊 Disease Information")

    if predicted_class in DISEASE_INFO:

      info = DISEASE_INFO[predicted_class]

      severity = info["severity"]

      if severity == "High":
         st.error(f"🔴 Severity : {severity}")
      elif severity == "Medium":
         st.warning(f"🟡 Severity : {severity}")
      elif severity == "None":

         st.success(f"🟢 Severity : {severity}")



      st.info(f"🌿 Treatment : {info['treatment']}")







# from pyngrok import ngrok
# ngrok.kill()

# # !streamlit run app.py &>/content/logs.txt&
# ngrok.set_auth_token("3FXsdEYIvJL5qg82Ntf7hKIfULf_4JGtPsn3P94JUTPwrvr4B")

# public_url = ngrok.connect(8501)
# print("Your URL:",public_url)
